### ISSUE TITLE
mamba_ssm import Mamba

### ISSUE THREAD

**Issue by saccy6** [wurenkai/UltraLight-VM-UNet#15]
你好 作者 非常感谢你对Mamba的贡献，但是这个ssm模块在哪里 我没有找到 该从哪里导入呢

**Comment by wurenkai** [comment]
Hi, you can find it in the official [mamba](https://github.com/state-spaces/mamba/tree/main) code.

**Comment by saccy6** [comment]
感谢 看到相同的问题了  已解决

**Comment by saccy6** [comment]
还有个问题 这个cuda必须11.7以上吗 我的是11.4可以跑吗

**Comment by wurenkai** [comment]
Currently mamba only supports Cuda11.7 or above, otherwise the environment installation will have problems and will not work properly.

**Comment by tiancpeng** [comment]
@wurenkai ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
How can this problem be solved? Thanks.

**Comment by wurenkai** [comment]
@tiancpeng Hi, according to this issue, there should be a problem with the environment installation. Use "nvcc -V" to check your own Cuda version. The pytorch installation in the '0. Main Environments.' installation guide is based on Cuda 11.7, so please install pytorch according to your own Cuda version, and note that the Cuda version should be greater than or equal to 11.7.

**Comment by tiancpeng** [comment]
@wurenkai The Python interpreter could not find the shared library file named libcudart.so.12. libcudart.so.12 is part of CUDA Toolkit 12. I also checked my cuda version which is 11.7, configured my environment according to read.me, and ran python train.py still having the above problem, can't fix it!
